### ISSUE TITLE
Move SpaceShuttle to its own repository

### ISSUE THREAD

**Issue by onox** [HerbyW/Antonov-Aircrafts#1]
It would be nice if the SpaceShuttle could be moved to its own repository. Then it can also be added to https://github.com/FGMEMBERS for example. To do while retaining the history, do this:

1. Make a copy of your local clone of this repository, call it `SpaceShuttle`:

    `cp -a Antonov-Aircrafts SpaceShuttle`

2. `cd SpaceShuttle` SpaceShuttle is a copy containing `AN-225`, `SpaceShuttle`, etc.

3. `cp LICENSE SpaceShuttle`. Here you copy the LICENSE file to the `SpaceShuttle` folder inside the `SpaceShuttle` repository.

4. `git add SpaceShuttle/LICENSE`

5. `git commit`

6. `git filter-branch --subdirectory-filter SpaceShuttle -- --all`. Your `SpaceShuttle` repository now only contains the files that were in the `SpaceShuttle` folder.

7. Now you can create a new repository on Github and then change the url of `origin` in your `SpaceShuttle` repository on your computer:

    `git remote set-url origin https://github.com/HerbyW/SpaceShuttle.git`

8. Push the `SpaceShuttle` repository on your computer to Github.

If you don't understand these instructions, but like the idea, then create a new empty SpaceShuttle repository on Github and add me as contributor, then I'll push the new repository.

**Comment by HerbyW** [comment]
HI, thanks for the hint. But for now I will leave it as it is, it is still in heavy development and for me it is better to have all together as I am new to FG and still have to learn a lot of things. My main priority is no error in any case and I will not move it to any repositiory with a different philosophy behind.
Greetings, HerbyW
